// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:farmer_auction_app/key.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FireBase_web_key,
    appId: '1:997923228224:web:efb821b9c0cbe0ff082da5',
    messagingSenderId: '997923228224',
    projectId: 'fir-77bb7',
    authDomain: 'fir-77bb7.firebaseapp.com',
    databaseURL: 'https://fir-77bb7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-77bb7.appspot.com',
    measurementId: 'G-QM28FNJY5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FireBase_android_key,
    appId: '1:997923228224:android:df26cde827d33286082da5',
    messagingSenderId: '997923228224',
    projectId: 'fir-77bb7',
    databaseURL: 'https://fir-77bb7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-77bb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FireBase_ios_key,
    appId: '1:997923228224:ios:9c492ab9bb6f290e082da5',
    messagingSenderId: '997923228224',
    projectId: 'fir-77bb7',
    databaseURL: 'https://fir-77bb7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-77bb7.appspot.com',
    androidClientId: '997923228224-69fvve4iode08t69ft1faqovks3kqreg.apps.googleusercontent.com',
    iosClientId: '997923228224-s46gj3h7f805mi1fl17kq613qkl97bhr.apps.googleusercontent.com',
    iosBundleId: 'com.farmdirect.farmstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Firebase_macos_key,
    appId: '1:997923228224:ios:178bf05121e6ff75082da5',
    messagingSenderId: '997923228224',
    projectId: 'fir-77bb7',
    databaseURL: 'https://fir-77bb7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-77bb7.appspot.com',
    androidClientId: '997923228224-69fvve4iode08t69ft1faqovks3kqreg.apps.googleusercontent.com',
    iosClientId: '997923228224-sacq635su9iuoctail5e6vh4vmapcbev.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerAuctionApp',
  );

}